kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: app-cluster-role
rules:
- apiGroups:
  - extensions
  resources:
  - podsecuritypolicies
  resourceNames:
  - app-psp
  verbs:
  - use
